### ISSUE TITLE
After exec playbook appears error in lineinfile

### ISSUE THREAD

**Issue by taller4gatos** [acandid/mariadb_apache_wordpress#1]
Hi, appears this error in the code 

> - name: Configure wp-config.php file Database Name
>   lineinfile:
>     path: "{{ web_path }}{{ wordpress_file_path }}"
>     regex: '^(.*)wordpress(.*)$'
>     line: "define( 'DB_NAME', '{{ db_name }}' );"

Error

> fatal: [51.15.86.26]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (lineinfile) module: regex Supported parameters include: attributes, backrefs, backup, content, create, delimiter, directory_mode, firstmatch, follow, force, group, insertafter, insertbefore, line, mode, owner, path, regexp, remote_src, selevel, serole, setype, seuser, src, state, unsafe_writes, validate"}

**Comment by acandid** [comment]
Hi

I saw that you changed the line below. You do not need to change this line, only the variables informed in the README.md file. These variables are located in the defaults or vars directory.

regex: '^(.)wordpress(.)$'

bug was fixed had put regex instead of regexp. Thank you so much for your help.

**Comment by acandid** [comment]
If you need help I will be happy to help. Have a great day
